### ISSUE TITLE
a == b not equivalent to b == a

### ISSUE THREAD

**Issue by sam0x17** [ysbaddaden/scrypt-crystal#3]
This might be by design, but I noticed that if the hash isn't placed on the left hand side in an equality comparison, you will get a different result. Intuitively I would think order shouldn't matter.

**Comment by ysbaddaden** [comment]
The left-hand side must be a Scrypt::Password and the right-hand side may be either a String or a Scrypt::Password.

This is required due to how Crystal handles overloaded operators, because if the left-hand side isn't a Scrypt::Password, then Crystal won't call the `Scrypt::Password#==(password)` method but for example `String#==(other)`, which can't work.

To avoid issues, always wrap the hash as a Scrypt::Password.

**Comment by sam0x17** [comment]
ok gotcha thanks
